services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://software.download.prss.microsoft.com/dbazure/Win8.1_English_x64.iso?t=16b6ae11-fe9c-4354-9a37-125c1a2fc7a3&P1=1770014427&P2=601&P3=2&P4=cx4I%2b63XTsNFbfVdu2mEEMeQOcs4iiQ2GexMrOPxM26rbtBcp92XaCcEv%2f34Wp7wIFtCce4J55jjtXOOMrse%2f6ZiY1oYytkrV7Ds%2fFceNIlRx1SCuShRxdadWCJr%2bauDEw%2fUc9U3HBLrsUqUalJ5hfIq6kbpT%2brn24ALMqTeVFVy2ByRAr2bZr341D4TZ4yxjYUtG8HtumUhzdAPObpiyYReTyk%2bcvukIUqmrMd98C%2ft%2f6LvwHVSJBj54HOIGuCBG45ca4BsnTJ9%2bct6sa49s4rQmuqsFKLyltimtWA7TytrpOP%2fhsXyQVtDjhhSaeGL24sRK7yW14BcYvsCWWlvqg%3d%3d"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
